version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "workout-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1laj6cqftfjbl"
s3_prefix = "workout-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
