AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  workout-app

  Sample SAM Template for workout-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  GetExercisesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: get_exercises/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /exercises
            Method: get
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ExercisesTable
      Environment:
        Variables:
          TABLE_NAME: !Ref ExercisesTable
  PostExerciseFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: post_exercise/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        PostExercise:
          Type: Api
          Properties:
            Path: /exercises
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ExercisesTable
      Environment:
        Variables:
          TABLE_NAME: !Ref ExercisesTable
  PostSetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: post_set/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        PostSet:
          Type: Api
          Properties:
            Path: /set
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SetsTable
      Environment:
        Variables:
          TABLE_NAME: !Ref SetsTable
  GetSetsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_sets/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        GetSets:
          Type: Api
          Properties:
            Path: /set
            Method: get
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SetsTable
      Environment:
        Variables:
          TABLE_NAME: !Ref SetsTable
  ExercisesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: Name
        Type: String
  SetsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: SetDate
          AttributeType: S
        - AttributeName: Exercise-SetNum-Key
          AttributeType: S
      KeySchema:
        - AttributeName: SetDate
          KeyType: "HASH"
        - AttributeName: Exercise-SetNum-Key
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ExercisesApi:
    Description: "API Gateway endpoint URL for Prod stage for get_exercises function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/exercises/"
  GetExercisesFunction:
    Description: "Get Exercises Lambda Function ARN"
    Value: !GetAtt GetExercisesFunction.Arn
  GetExercisesFunctionIamRole:
    Description: "Implicit IAM Role created for Get Exercises function"
    Value: !GetAtt GetExercisesFunctionRole.Arn
  PostExerciseFunction:
    Description: "Post Exercise Lambda Function ARN"
    Value: !GetAtt PostExerciseFunction.Arn
  PostExerciseFunctionIamRole:
    Description: "Implicit IAM Role created for Post Exercise function"
    Value: !GetAtt PostExerciseFunctionRole.Arn
  PostSetFunction:
    Description: "Post Set Lambda Function ARN"
    Value: !GetAtt PostSetFunction.Arn
  PostSetFunctionIamRole:
    Description: "Implicit IAM Role created for Post Set function"
    Value: !GetAtt PostSetFunctionRole.Arn
  GetSetsFunction:
    Description: "Get Sets Lambda Function ARN"
    Value: !GetAtt GetSetsFunction.Arn
  GetSetsFunctionIamRole:
    Description: "Implicit IAM Role created for Get Sets function"
    Value: !GetAtt GetSetsFunctionRole.Arn
